version: "3.8"

services:
  web:
    build: .
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./db:/app/database
    environment:
      - DATABASE_URL=sqlite:///./db/predictions.db
